AI-READI/fairhub-portal

- .github/workflows/deploy-staging.yml
- components/card/CollapsibleCard.vue
- layouts/default.vue
- nuxt.config.ts
- package.json
- pages/index.vue
- pages/submit.vue
- server/api/__sitemap__/urls.ts
- server/api/datasets/index.get.ts
- types/dataset.d.ts
- yarn.lock
In addition the following features are added to this PR
- Add support for generating sitemaps
- Add support for dynamic robots.txt
- Update style of collapsible cards
> ✨ feat: add submit page

- app.vue
- nuxt.config.ts
- package.json
- pages/datasets/[datasetid]/index.vue
- yarn.lock
> ✨ feat: add basic nuxt schema

- composables/useMsal.ts
- nuxt.config.ts
- package.json
- pages/login.vue
- plugins/Msal.ts
- staticwebapp.config.json
- yarn.lock
Use MSAL.js to kick off the sign up / sign in process.
> ✨ feat: use MSAL.js for authentication

- components/button/AuthenticationTrigger.vue
- composables/useAccount.ts
- composables/useAuthClient.ts
- layouts/default.vue
- nuxt.config.ts
- pages/login.vue
- plugins/Msal.ts
* Rename authentication composable
* Add auth config for local development
* Add login button component
> ♻️  refactor: authentication improvements

- dev/datasetRecord.json
- package.json
- scripts/edit-record.ts
- server/api/datasets/[datasetid]/index.get.ts
- server/api/datasets/index.get.ts
For some reason, the DB was storing the JSON as a string rather than the Postgres json type. Fixing this issue.
> 🐛 fix: convert db record to native json

- .env.example
- package.json
- yarn.lock
> ⬆️ chore (deps): upgrade nuxt

- pages/datasets/[datasetid]/index.vue
Reverting to the last commit to bring back the download workflow
> fix: Update download to use the new route

- nuxt.config.ts
Update authentication config to use new login workflow without registration.
> 🐛 fix: fix authentication config

- components/download/AttestationForm.vue
- components/download/FolderSelector.vue
- nuxt.config.ts
- server/routes/logout.ts
* Adds handling for logging out of both the session and from Entra
* Adds link to cyber security guidelines
* Restructures the download card to move the checkbox to the left of the folder description
> Add logout handling and update requests

- pages/datasets/[datasetid]/access/license.vue
- pages/datasets/[datasetid]/access/research-purpose.vue
- pages/datasets/[datasetid]/access/submitted.vue
Minor fixes to the download workflow:
* Provide better feedback in the research purpose form
* Improve prominence of messaging on how to obtain data during the open house
Style changes for open house messaging:
> Minor download fixes

- nuxt.config.ts
Add authentication config for the production environment.
> 🔨 chore: add production authentication config

- dev/datasetRecord.json
- pages/datasets/[datasetid]/index.vue
- server/api/datasets/[datasetid]/index.get.ts
- types/dataset.d.ts
* ✨ feat: add support for basic view counts
* 🗑️ chore: remove console logs
> ✨ feat: add support for basic view counts

- pages/datasets/[datasetid]/access/submitted.vue
- pages/datasets/[datasetid]/index.vue
* chore: fix dqd link
* feat: add link to return to dataset home
> chore: fix dqd link

- components/files/FolderViewer.vue
- types/dataset.d.ts
- Relation type URL variable got fixed
- Directory description is not required
> fix: relation type structure

- composables/useDownloadRequest.ts
- pages/datasets/[datasetid]/access/request/[requestid].vue
- server/api/downloads/key/[requestid]/index.get.ts
- server/api/downloads/request/[requestid]/index.get.ts
Add a page with instructions for how to download the dataset.
> feat: add download landing page

- pages/datasets/[datasetid]/access/request/[requestid].vue
Work around problems with downloading key file.
> fix: copy key to clipboard

- app.vue
- assets/css/tailwind.css
- pages/datasets/[datasetid]/index.vue
- server/api/viewCount/[datasetid].get.ts
Add endpoint gets total view from umami api
adjust color theme for the spinner
adjust color theme for the select buttons
>  chore: 🔧 update website view count in dashboard

- pages/datasets/[datasetid]/access/request/[requestid].vue
- server/api/downloads/key/[requestid].get.ts
Improve download instructions:
* remove command line sftp instructions
* add FileZilla download instructions
* attempt to fix SSH key download
> ✨ feat: improved download instructions

- middleware/auth.ts
- nuxt.config.ts
- pages/datasets/[datasetid]/access/request/[requestid].vue
- server/api/downloads/key/[requestid].get.ts
Merge download improvements from staging
> Download improvements

- prisma/schema.prisma
- server/api/downloads/request/create.post.ts
Add state to store whether a download request has been approved.
> 🔨 chore: download request approval

- components/download/AgreementList.vue
- pages/datasets/[datasetid]/index.vue
- prisma/schema.prisma
- server/api/datasets/[datasetid]/agreements.get.ts
- server/api/downloads/request/create.post.ts
Merge changes for download authorization from staging
> Prod authorization status

- pages/datasets/[datasetid]/access/diabetes-research.vue
- pages/datasets/[datasetid]/access/research-purpose.vue
Feedback from Shannon regarding some textual modifications.
> chore: DAC review feedback

- nuxt.config.ts
- server/api/datasets/[datasetid]/index.get.ts
- server/api/datasets/index.get.ts
Add a dataset embargo for the requested release date/times.
Staging : Wed Nov 06 2024 17:30:00 GMT-0800 (Pacific Standard Time)
Prod: Fri Nov 07 2024 02:00:00 GMT-0800 (Pacific Standard Time)
> ✨ feat: add study embargo

- components/download/FolderSelector.vue
Display the file count and folder size in the download folder selector when available.
> Add Size to Folder Selector

- modules/dashboard/config/modules-manifest.ts
- modules/dashboard/config/modules/phenotype-race-by-phase.json
- modules/dashboard/config/modules/phenotype-recruitment-by-phase.json
- modules/dashboard/config/modules/race-phenotype-by-phase.json
- modules/dashboard/config/modules/race-recruitment-by-phase.json
- modules/dashboard/config/modules/race-sex-by-phase.json
- stores/dashboard.ts
Updated dashboard metadata for year 2 visualizations.
> ✨ feat: dashboard update year 2

- pages/datasets/[datasetid]/access/index.vue
we had a user from Germany who was confused about the login process so we modified that instruction
> revising login instructions for CILogon

- components/download/FolderSelector.vue
- components/files/FolderViewer.vue
- pages/datasets/[datasetid]/access/request/[requestid].vue
- prisma/schema.prisma
- server/api/downloads/request/[requestid]/index.get.ts
* Displays the token expiration date so users know when they must complete their download
* Fixes the prettybyte size calculation
> Expiration date

- components/download/FolderSelector.vue
- components/files/FolderViewer.vue
- nuxt.config.ts
- pages/datasets/[datasetid]/access/index.vue
- pages/datasets/[datasetid]/access/request/[requestid].vue
- prisma/schema.prisma
- server/api/downloads/request/[requestid]/index.get.ts
- server/routes/login.get.ts
- types/download.d.ts
Adding fixes to accommodate IdPs that do not return email and providing users the date their SAS token expires.
> CILogon and token expiration

- pages/datasets/[datasetid]/access/request/[requestid].vue
Apparently there was a bug with the way I was importing the daysjs lib in the previous commit.
> fix: user daysjs import

- pages/datasets/[datasetid]/access/request/[requestid].vue
Apparently the import style used previously was not acceptable in Azure.
> fix: use differnt import style

- pages/datasets/[datasetid]/access/request/[requestid].vue
- prisma/schema.prisma
Missed the change to make `expires_at` optional
> Fix prisma schema to allow for nullable `expires_at`

- layouts/default.vue
- pages/datasets/[datasetid]/index.vue
- Added banner to all pages
-Fixed scrollable behavior of the pages in case of overflow
> feat: add banner

- layouts/default.vue
- package.json
- scripts/insert.ts
- Added banner to all pages
- Fixed scrollability behavior of the pages in case of overflow
> feat: ✨ add a notice banner for the repository

- pages/datasets/[datasetid]/index.vue
- server/api/datasets/[datasetid]/dataset_description.json.get.ts
- added an api that fetches the dataset json from the dataset and passed to json ld(indirectly), to improve the machine readability
> fix: ✨add dataset_description to the json ld

- components/side/CitationViewer.vue
- components/side/DatasetSize.vue
- pages/datasets/[datasetid]/index.vue
- pages/index.vue
- types/dataset.d.ts
Add support for a mini dataset for model training.
> feat: add mini dataset indicators

- components/download/AttestationForm.vue
- pages/datasets/[datasetid]/access/license.vue
Adds new attestations regarding US counties of concern.
> New attestations

- components/dashboard/DashboardView.vue
- components/download/AgreementList.vue
- components/download/LicenseForm.vue
- components/lottie/LottieLoader.vue
- components/side/CitationViewer.vue
- dev/related_identifier.json
- dev/usage-statistics.md
- modules/dashboard/config/modules-manifest.ts
- modules/dashboard/config/modules/phenotype-race-by-phase.json
- modules/dashboard/config/modules/phenotype-recruitment-by-phase.json
- modules/dashboard/config/modules/race-phenotype-by-phase.json
- modules/dashboard/config/modules/race-recruitment-by-phase.json
- modules/dashboard/config/modules/race-sex-by-phase.json
- pages/datasets/[datasetid]/access/index.vue
- pages/datasets/[datasetid]/access/request/[requestid].vue
- server/api/datasets/[datasetid]/agreements.get.ts
- server/api/downloads/key/[requestid].get.ts
- server/utils/getOrCreateUserDetails.ts
- types/download.d.ts
- Commented out the citation formating request
- Fix yarn errors as they were in the multiple pages
> fix: ✨ comment out citation and fix yarn formatting

- components/dashboard/DashboardView.vue
- components/download/AgreementList.vue
- components/download/LicenseForm.vue
- components/lottie/LottieLoader.vue
- components/side/CitationViewer.vue
- dev/related_identifier.json
- dev/usage-statistics.md
- modules/dashboard/config/modules-manifest.ts
- modules/dashboard/config/modules/phenotype-race-by-phase.json
- modules/dashboard/config/modules/phenotype-recruitment-by-phase.json
- modules/dashboard/config/modules/race-phenotype-by-phase.json
- modules/dashboard/config/modules/race-recruitment-by-phase.json
- modules/dashboard/config/modules/race-sex-by-phase.json
- pages/datasets/[datasetid]/access/index.vue
- pages/datasets/[datasetid]/access/request/[requestid].vue
- server/api/datasets/[datasetid]/agreements.get.ts
- server/api/downloads/key/[requestid].get.ts
- server/utils/getOrCreateUserDetails.ts
- types/download.d.ts
Reverts AI-READI/fairhub-portal#208
> Revert "fix: ✨ comment out citation and fix yarn formatting"
